"""
GitHub API integration — creates fix branches and opens Pull Requests automatically.
"""
import os
from typing import Optional


async def create_fix_pr(
    repo_name: str,
    base_branch: str,
    fixes: list[dict], # list of {file_info, fix}
) -> Optional[str]:
    """Create a new branch with all fixed files in a SINGLE commit and open a Pull Request."""
    token = os.getenv("GITHUB_TOKEN")
    if not token or not fixes:
        return None

    try:
        from github import Github, InputGitTreeElement
        import time
        import uuid

        g = Github(token)
        repo = g.get_repo(repo_name)

        # 1. Skip files that have no changes to prevent empty PRs
        actual_fixes = []
        for item in fixes:
            original = item["file_info"].get("content", "")
            fixed = item["fix"].get("fixed_content", "")
            if fixed and fixed != original:
                actual_fixes.append(item)
        
        if not actual_fixes:
            print("[GitHub API] No actual changes detected across any files. Skipping PR.")
            return None

        # 2. Create a unique fix branch
        push_id = str(uuid.uuid4())[:6]
        fix_branch = f"ai-gitops-fix/group-{int(time.time())}-{push_id}"

        # 3. Get base branch info
        base_ref = repo.get_branch(base_branch)
        base_sha = base_ref.commit.sha
        base_commit = repo.get_git_commit(base_sha)
        base_tree = base_commit.tree

        # 4. Prepare tree elements for a SINGLE commit
        tree_elements = []
        body_parts = ["## 🤖 AI GitOps Agent — Automated Multi-File Fix\n"]
        body_parts.append(f"Analyzing and automatically healing the whole push on `{base_branch}`.\n")

        for item in actual_fixes:
            file_info = item["file_info"]
            fix = item["fix"]
            path = file_info["path"]
            
            fixed_content = fix.get("fixed_content", "")
            description = fix.get("description", "AI GitOps Agent auto-fix")

            # Add to tree elements
            tree_elements.append(InputGitTreeElement(path, '100644', 'blob', content=fixed_content))
            
            # Add to PR body
            body_parts.append(f"### 📄 `{path}`")
            body_parts.append(f"**Issues Fixed:**")
            issues = file_info.get('issues', [])
            if issues:
                body_parts.append("\n".join(f"- [{i['severity'].upper()}] {i['description']}" for i in issues))
            else:
                body_parts.append("- No static issues detected, but architectural improvements were applied.")
            
            body_parts.append(f"\n**Fixes Applied:**")
            fixes_list = "\n".join(f"- {f}" for f in fix.get("fixes_applied", []))
            body_parts.append(fixes_list if fixes_list else "- Comprehensive configuration hardening.")
            body_parts.append("\n---\n")

        # 5. Create new tree and commit
        new_tree = repo.create_git_tree(tree_elements, base_tree)
        new_commit = repo.create_git_commit(
            message=f"🤖 ai-gitops-agent: auto-fix {len(actual_fixes)} file(s)",
            tree=new_tree,
            parents=[base_commit]
        )

        # 6. Create the branch (ref) pointing to the new commit
        repo.create_git_ref(ref=f"refs/heads/{fix_branch}", sha=new_commit.sha)

        body_parts.append("*This PR was automatically generated by the AI GitOps Agent. Please review before merging.*")

        # 7. Create the single PR
        pr = repo.create_pull(
            title=f"🤖 [AI Fix] Grouped fixes for {len(actual_fixes)} file(s) on {base_branch}",
            body="\n".join(body_parts),
            head=fix_branch,
            base=base_branch,
        )
        return pr.html_url

    except Exception as e:
        print(f"[GitHub API] Multi-PR creation failed: {e}")
        import traceback
        traceback.print_exc()
        return None

    except Exception as e:
        print(f"[GitHub API] Multi-PR creation failed: {e}")
        import traceback
        traceback.print_exc()
        return None
